/********************************/
/* Author  : Mo'men Hesham		*/
/* Version : V01				*/
/********************************/

#ifndef MDMA_CONFIG_H
#define MDMA_CONFIG_H

/* Options :CHANNEL_1 .... CHANNEL_7 */
#define CHANNEL_ID				CHANNEL_1

/* Options: ENABLE_MEMORY_TO_MEMORY
			DISABLE_MEMORY_TO_MEMORY
*/
#define MEMORY_TO_MEMORY_MODE	ENABLE_MEMORY_TO_MEMORY
/* Options: PRIORITY_LOW
			PRIORITY_MEDIUM
			PRIORITY_HIGH
			PRIORITY_VERY_HIGH
*/
#define CHANNEL_PRIORITY_LEVEL	PRIORITY_VERY_HIGH

/* Options: SIZE_8_BIT
			SIZE_16_BIT
			SIZE_32_BIT
*/
#define MEMORY_SIZE				SIZE_32_BIT
#define	PERIPHERAL_SIZE			SIZE_32_BIT

/* Options: INCREMENT_MODE
			NO_INCREMENT_MODE
*/
#define MEMORY_MODE				INCREMENT_MODE
#define PERIPHERAL_MODE			INCREMENT_MODE

/* Options: ENABLE_CIRCULAR_MODE
			DISABLE_CIRCULAR_MODE
*/
#define CIRCULAR_MODE			DISABLE_CIRCULAR_MODE

/* Options: READ_FROM_MEMORY
			READ_FROM_PERIPHERAL
*/
#define DATA_TRANSFER_DIRECTION		READ_FROM_PERIPHERAL

/* Options:  TRANSFER_COMPLETE_HALF_ERROR
             TRANSFER_COMPLETE_ERROR
			 TRANSFER_HALF_ERROR
             TRANSFER_COMPLETE_HALF
             TRANSFER_COMPLETE
             TRANSFER_HALF
             TRANSFER_ERROR
             NO_FLAGS_SET				
*/
#define INTERUPT_FLAGS	TRANSFER_HALF

#endif
